version: "3.3"

services:

  chain-4:
    environment:
      - ALCHEMY_API_KEY=$ALCHEMY_API_KEY
    container_name: chain-4-test
    image: trufflesuite/ganache-cli:latest
    command: "--chainId 4 --fork https://eth-rinkeby.alchemyapi.io/v2/$ALCHEMY_API_KEY --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --hostname 0.0.0.0 --blockTime 3 --verbose"
    ports:
      - "8547:8545"
  chain-42:
    environment:
      - ALCHEMY_API_KEY=$ALCHEMY_API_KEY
    container_name: chain-42-test
    image: trufflesuite/ganache-cli:latest
    command: "--chainId 42 --fork https://eth-kovan.alchemyapi.io/v2/$ALCHEMY_API_KEY --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --host 0.0.0.0 --blockTime 3 --verbose"
    ports:
      - "8546:8545"

  graph-node-4:
    container_name: graph-node-4-test
    image: graphprotocol/graph-node:v0.25.0
    ports:
      - "8010:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres-4
      - chain-4
    environment:
      postgres_host: postgres-4
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://chain-4:8545"
      GRAPH_LOG: info

  postgres-4:
    container_name: postgres-4-test
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node

  graph-node-42:
    container_name: graph-node-42-test
    image: graphprotocol/graph-node:v0.25.0
    ports:
      - "9010:8000"
      - "9001:8001"
      - "9020:8020"
      - "9030:8030"
      - "9040:8040"
    depends_on:
      - ipfs
      - postgres-42
      - chain-42
    environment:
      postgres_host: postgres-42
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://chain-42:8545"
      GRAPH_LOG: info

  postgres-42:
    container_name: postgres-42-test
    image: postgres
    ports:
      - "5433:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node

  ipfs:
    container_name: ipfs-test
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"

