name: Create and publish Docker images

on:
  push:
    branches:
      - "test-sops"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Setup Sops
        uses: mdgreenwald/mozilla-sops-action@v1.2.0
        with:
          version: '3.7.2'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Decrypt Testnet Secrets
        id: decrypt
        run: sops -d ops/env/testnet/secrets.staging.json > ops/testnet/staging/tfvars.json

      - name: Terraform Init
        id: init
        working-directory: ./ops/testnet/staging
        run: terraform init